# Dependabot Workflow
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/dataset/"
    schedule:
      interval: "daily"
